import type { BarangayData } from "./types";

export const initialBarangays: BarangayData[] = [
  {
    id: "1",
    name: "Addition Hills",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 280, y: 425 },
  },
  {
    id: "2",
    name: "Bagong Silang",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 215, y: 280 },
  },
  {
    id: "3",
    name: "Barangka Drive",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 290, y: 750 },
  },
  {
    id: "4",
    name: "Barangka Ibaba",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 300, y: 810 },
  },
  {
    id: "5",
    name: "Barangka Ilaya",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 390, y: 785 },
  },
  {
    id: "6",
    name: "Barangka Itaas",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 335, y: 780 },
  },
  {
    id: "7",
    name: "Buayang Bato",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 173, y: 327 },
  },
  {
    id: "8",
    name: "Burol",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 440, y: 800 },
  },
  {
    id: "9",
    name: "Daang Bakal",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 180, y: 240 },
  },
  {
    id: "10",
    name: "Hagdang Bato Itaas",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 210, y: 360 },
  },
  {
    id: "11",
    name: "Hagdang Bato Libis",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 250, y: 340 },
  },
  {
    id: "12",
    name: "Harapin Ang Bukas",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 180, y: 300 },
  },
  {
    id: "13",
    name: "Highway Hills",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 450, y: 600 },
  },
  {
    id: "14",
    name: "Hulo",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 220, y: 765 },
  },
  {
    id: "15",
    name: "Mabini-J. Rizal",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 105, y: 440 },
  },
  {
    id: "16",
    name: "Malamig",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 350, y: 650 },
  },
  {
    id: "17",
    name: "Mauway",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 350, y: 500 },
  },
  {
    id: "18",
    name: "Namayan",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 90, y: 575 },
  },
  {
    id: "19",
    name: "New Zañiga",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 190, y: 475 },
  },
  {
    id: "20",
    name: "Old Zañiga",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 140, y: 480 },
  },
  {
    id: "21",
    name: "Pag-Asa",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 145, y: 325 },
  },
  {
    id: "22",
    name: "Plainview",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 250, y: 640 },
  },
  {
    id: "23",
    name: "Pleasant Hills",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 330, y: 370 },
  },
  {
    id: "24",
    name: "Poblacion",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 162, y: 400 },
  },
  {
    id: "25",
    name: "San Jose",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 198, y: 525 },
  },
  {
    id: "26",
    name: "Vergara",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 140, y: 640 },
  },
  {
    id: "27",
    name: "Wack-Wack Greenhills",
    waterLevel: 0,
    personnel: { srr: 0, health: 0, log: 0 },
    coordinates: { x: 450, y: 300 },
  },
];
